{
 "title": "MySQL-Clone-Backup",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance_name",
    "query": "select instance_name from `tb_instance` where is_clone = 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Backup State",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select fm.state as '备份状态', count(*) as 'Count'\n  from `full_backup_metadata` as fm\n  JOIN `tb_instance` as tb on fm.tb_instance_id=tb.id where tb.instance_name = '${instance_name}'\nGROUP BY fm.state"
    }
   ]
  },
  {
   "title": "Clone DB Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) from `tb_instance` where is_clone = 1;"
    }
   ]
  },
  {
   "title": "Backup Mode Count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select fm.backup_type as '备份类型', count(*) as 'full'\n  from `full_backup_metadata` as fm \n  JOIN `tb_instance` as tb on fm.tb_instance_id=tb.id where fm.backup_type = 'full' and tb.instance_name = '${instance_name}'"
    },
    {
     "rawSql": "select fm.backup_type as '备份类型', count(*) as 'binlog'\n  from `full_backup_metadata` as fm \n  JOIN `tb_instance` as tb on fm.tb_instance_id=tb.id where fm.backup_type = 'binlog' and tb.instance_name = '${instance_name}'"
    }
   ]
  },
  {
   "title": "Clone Backup",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": " select tb.instance_id as '实例 ID',\n       tb.instance_name as '实例名称',\n       fm.backup_name as '备份名',\n       fm.bucket_name as 'Bucket 名称',\n       fm.state as '备份状态',\n       fm.backup_size as '备份大小',\n       fm.start_time as '备份开始时间',\n       fm.end_time as '备份结束时间',\n       fm.overdue_day as '备份过期天数'\n  from `full_backup_metadata` as fm\n  JOIN `tb_instance` as tb on fm.tb_instance_id=tb.id\n where backup_type='full' and fm.is_delete = 0 and tb.instance_name = '${instance_name}'\n order by fm.created_at desc"
    }
   ]
  },
  {
   "title": "Binlog Backup",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "select tb.instance_id as '实例 ID',\n       tb.instance_name as '实例名称',\n       fm.backup_name as '备份名',\n       fm.bucket_name as 'Bucket 名称',\n       fm.state as '备份状态',\n       fm.backup_size as '备份大小',\n       fm.start_time as '备份开始时间',\n       fm.end_time as '备份结束时间',\n       fm.overdue_day as '备份过期天数'\n  from `full_backup_metadata` as fm\n  JOIN `tb_instance` as tb on fm.tb_instance_id=tb.id\n where backup_type='binlog' and fm.is_delete = 0 and tb.instance_name = '${instance_name}'\n order by fm.start_time desc;"
    }
   ]
  }
 ]
}